// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using daw_en_2324.Models;

#nullable disable

namespace daw_en_2324.Migrations
{
    [DbContext(typeof(PSAContext))]
    [Migration("20240116151323_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("daw_en_2324.Models.CurricularProgram", b =>
                {
                    b.Property<int>("CurricularProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurricularProgramId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CurricularProgramId");

                    b.ToTable("CurricularPrograms");
                });

            modelBuilder.Entity("daw_en_2324.Models.Enrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrollmentId"), 1L, 1);

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("UcId")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UcId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("daw_en_2324.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("daw_en_2324.Models.Uc", b =>
                {
                    b.Property<int>("UcId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UcId"), 1L, 1);

                    b.Property<int?>("CurricularProgramId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UcId");

                    b.HasIndex("CurricularProgramId");

                    b.ToTable("Ucs");
                });

            modelBuilder.Entity("daw_en_2324.Models.Enrollment", b =>
                {
                    b.HasOne("daw_en_2324.Models.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("daw_en_2324.Models.Uc", "Uc")
                        .WithMany("Enrollments")
                        .HasForeignKey("UcId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Uc");
                });

            modelBuilder.Entity("daw_en_2324.Models.Uc", b =>
                {
                    b.HasOne("daw_en_2324.Models.CurricularProgram", null)
                        .WithMany("Ucs")
                        .HasForeignKey("CurricularProgramId");
                });

            modelBuilder.Entity("daw_en_2324.Models.CurricularProgram", b =>
                {
                    b.Navigation("Ucs");
                });

            modelBuilder.Entity("daw_en_2324.Models.Student", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("daw_en_2324.Models.Uc", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
